// Generates src/version.ts from package.json so the in-app version label can
// never drift from the published package version. Runs automatically before
// every build via the `prebuild` npm lifecycle hook.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = String(pkg.version || '0.0.0');

const contents = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json "version" on every build (prebuild hook).
export const DEVNOTES_VERSION = '${version}';
`;

writeFileSync(join(root, 'src', 'version.ts'), contents);
console.log(`[devnotes] synced src/version.ts -> ${version}`);
